# Generated by Django 4.2.7 on 2025-12-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('luxury', 'Luxury')], max_length=50)),
                ('total_seats', models.IntegerField(default=40)),
                ('available_seats', models.IntegerField(default=40)),
                ('bus_number', models.CharField(blank=True, max_length=20)),
                ('bus_image', models.ImageField(blank=True, null=True, upload_to='buses/')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_buses', to='planner.destination')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_buses', to='planner.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('low', 'Low Cost'), ('medium', 'Medium Cost'), ('high', 'High Cost')], max_length=20)),
                ('total_seats', models.IntegerField(default=180)),
                ('available_seats', models.IntegerField(default=180)),
                ('description', models.TextField(blank=True)),
                ('flight_image', models.ImageField(blank=True, null=True, upload_to='flights/')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='planner.destination')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='planner.destination')),
            ],
        ),
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('economy', 'Economy'), ('suv', 'SUV'), ('luxury', 'Luxury'), ('van', 'Van')], max_length=50)),
                ('seats', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('interior_images', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_cars', to='planner.destination')),
            ],
        ),
    ]