# Generated by Django 4.2.7 on 2025-12-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departing_trips', to='planner.destination', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_trips', to='planner.destination', verbose_name='To'),
        ),
    ]
