# Generated by Django 4.2.7 on 2025-12-26 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_tripplan_origin_alter_tripplan_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_by_admin',
            field=models.BooleanField(default=False, help_text='Whether this hotel was created by admin'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='busservice',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Price in MMK', max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='price_per_day',
            field=models.DecimalField(decimal_places=0, help_text='Price in MMK per day', max_digits=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Price in MMK', max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('budget', 'Budget (Under 50,000 MMK)'), ('medium', 'Medium (50,000 - 150,000 MMK)'), ('luxury', 'Luxury (150,000+ MMK)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=0, help_text='Price in MMK (Myanmar Kyat)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
