# Generated by Django 4.2.7 on 2025-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_destination_latitude_destination_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_real_hotel',
            field=models.BooleanField(default=False, help_text='Is this a real hotel from Google Maps?'),
        ),
    ]
