# Generated by Django 4.2.7 on 2025-12-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_hotel_google_place_id_hotel_is_real_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
