# Generated by Django 4.2.7 on 2025-12-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_hotel_check_in_time_hotel_check_out_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='IATA airline code', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_domestic', models.BooleanField(default=False, help_text='Whether this airline is default for domestic flights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_map',
            field=models.JSONField(default=dict, help_text='JSON representation of seat layout and availability'),
        ),
        migrations.AddField(
            model_name='destination',
            name='default_airlines',
            field=models.ManyToManyField(blank=True, help_text='Default airlines for this destination', to='planner.airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='planner.airline'),
        ),
    ]
