# Generated by Django 4.2.7 on 2026-01-03 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0007_airline_flight_seat_map_destination_default_airlines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus')], max_length=10)),
                ('transport_id', models.IntegerField()),
                ('seat_number', models.CharField(max_length=10)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='planner.tripplan')),
            ],
            options={
                'ordering': ['transport_type', 'transport_id', 'seat_number'],
                'unique_together': {('transport_type', 'transport_id', 'seat_number')},
            },
        ),
    ]
