# Generated by Django 5.2.3 on 2026-01-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_airline_flight_seat_map_destination_default_airlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='accommodation_preference',
            field=models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('luxury', 'Luxury')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='selected_plan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='budget_range',
            field=models.CharField(choices=[('low', 'Low Budget'), ('medium', 'Medium Budget'), ('high', 'High Budget')], default='medium', max_length=10),
        ),
    ]
