# Generated by Django 5.2.3 on 2026-01-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_bookedseat'),
        ('planner', '0008_tripplan_accommodation_preference_and_more'),
    ]

    operations = [
    ]
