# Generated by Django 5.2.3 on 2026-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_merge_20260103_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='accommodation_preference',
        ),
        migrations.RemoveField(
            model_name='tripplan',
            name='selected_plan_id',
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='budget_range',
            field=models.CharField(choices=[('low', 'Budget'), ('medium', 'Medium'), ('high', 'Luxury')], max_length=20),
        ),
    ]
