# Generated by Django 5.2.3 on 2026-01-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_remove_tripplan_accommodation_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_plans', models.JSONField(default=list)),
                ('custom_activities', models.JSONField(default=list)),
                ('weather_data', models.JSONField(blank=True, default=dict)),
                ('weather_last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='planner.tripplan')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('weather_icon', models.CharField(blank=True, max_length=50)),
                ('weather_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.itinerary')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['day_number', 'time'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('cultural', 'Cultural Explorer'), ('adventure', 'Adventure Seeker'), ('relaxed', 'Relaxed Wanderer')], max_length=50)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField(default=3)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('highlights', models.JSONField(default=list)),
                ('sample_day', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to='planner.destination')),
            ],
            options={
                'ordering': ['style', 'name'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='travel_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.travelplan'),
        ),
    ]
