# Generated by Django 5.2.3 on 2026-01-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_itinerary_activity_travelplan_itinerary_travel_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='travel_plan',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='TravelPlan',
        ),
    ]
